### ISSUE TITLE
Add support for whisper-jax

### ISSUE THREAD

**Issue by pipip** [rhasspy/wyoming-faster-whisper#14]
Whisper JAX is supposed to be even faster than faster-whisper. TPU sounds also promisimg eventho Google Coral TPU is not supported.

https://github.com/sanchit-gandhi/whisper-jax

Is there any way to couple this with wyoming as well to use it in a Homme Assistant Assit pipeline?

**Comment by ser** [comment]
What hardware would you use then?

**Comment by pipip** [comment]
Google Coral TPU (e.g. M.2 Accelerator)

**Comment by ser** [comment]
There is no chance it works on Coral, not enough memory.

**Comment by synesthesiam** [comment]
Sorry, this isn't something I would be able to support
