### ISSUE TITLE
wyoming-(normal)-whisper?

### ISSUE THREAD

**Issue by ser** [rhasspy/wyoming-faster-whisper#15]
As faster whisper does not work on AMD GPUs and as I can read there is no plan to support it, would not it be useful to have wyoming-whisper as well?

**Comment by dbolger** [comment]
+1, I'll link these issues since they seem relevant to this conversation:
- https://github.com/OpenNMT/CTranslate2/issues/1072
- https://github.com/SYSTRAN/faster-whisper/issues/162#issuecomment-1514767030

**Comment by ser** [comment]
I have just written a Wyoming connector to Whisper API which allows utilising multiple engines and models via Whisper.cpp: https://github.com/ser/wyoming-whisper-api-client

**Comment by dbolger** [comment]
Awesome, thank you for sharing :)
