### ISSUE TITLE
No containers available for the new git tags

### ISSUE THREAD

**Issue by Omar007** [rhasspy/wyoming-faster-whisper#18]
The git tags in this repo (1.0.2 and 1.1.0) do not have a corresponding container available on https://hub.docker.com/r/rhasspy/wyoming-whisper.  
(and conversely, fwiw, the available container tags (0.0.3 and 1.0.0) do not have a corresponding tag in this repo).  

It'd be nice if new versions/tags get a corresponding container build available.

**Comment by synesthesiam** [comment]
Update to 2.0.0 :+1:
