### ISSUE TITLE
Container crashes with "Illegal instruction"

### ISSUE THREAD

**Issue by pacjo** [rhasspy/wyoming-faster-whisper#21]
I tried running container on my server, but I'm getting this in logs:
```
[...]
/run.sh: line 5:     6 Illegal instruction     (core dumped) python3 -m wyoming_faster_whisper --uri 'tcp://0.0.0.0:10300' --data-dir /data --download-dir /data "$@"
/run.sh: line 5:     7 Illegal instruction     (core dumped) python3 -m wyoming_faster_whisper --uri 'tcp://0.0.0.0:10300' --data-dir /data --download-dir /data "$@"
/run.sh: line 5:     7 Illegal instruction     (core dumped) python3 -m wyoming_faster_whisper --uri 'tcp://0.0.0.0:10300' --data-dir /data --download-dir /data "$@"
[...]
```

The hardware is old with no AVX and especially AVX2 support (I remember it being an issue with Immich).

I also tried https://docs.linuxserver.io/images/docker-faster-whisper/ which too fails to run (but no meaningfull logs there).

**Comment by synesthesiam** [comment]
AVX support is required, as this relies on [CTranslate2](https://github.com/OpenNMT/CTranslate2)

**Comment by pacjo** [comment]
Ok, thanks for confirmation.
