### ISSUE TITLE
Reason to include faster_whisper in this Repo?

### ISSUE THREAD

**Issue by ChiefJReloaded** [rhasspy/wyoming-faster-whisper#26]
Is there a reason to include parts of the sources for [faster-whisper](https://github.com/SYSTRAN/faster-whisper) in this repository instead of listing it as a dependency in `requirements.txt`? 
If the reason is version-pinning, this could be done as a dependency as well, but would make it easier to profit from new features/improvements.

**Comment by synesthesiam** [comment]
Yes, faster-whisper pulls in the [av package](https://pypi.org/project/av/) and uses ffmpeg by default for audio conversion. This is unnecessary, as the Wyoming protocol only streams raw audio, so I decided to avoid bloating `wyoming-faster-whisper` (and its container/add-on).

**Comment by ChiefJReloaded** [comment]
Ah okay, that sounds like a reasonable decision. Thanks for answering.
The reason for my question was mostly issues like [#23](https://github.com/rhasspy/wyoming-faster-whisper/issues/23), [#10](https://github.com/rhasspy/wyoming-faster-whisper/issues/10), [#6](https://github.com/rhasspy/wyoming-faster-whisper/issues/6) and [#5](https://github.com/rhasspy/wyoming-faster-whisper/issues/5).
These all ask for other models including distilled models, which would be supported by newer faster-whisper versions. GPU support would be another reason to maybe update the sources used from faster-whisper.

**Comment by rvsh2** [comment]
Yeah, maybe you are not bloating container but instead the update is very difficult. For example I would like to use model large_v3 and in this case I cannot do it straightforward to just update faster whisper to newest version and still use wyoming. I think the approach to use standard libraries is much more efficient. You are just one person and to update all the changes that were made in original projects (like openwakeword or faster-whisper) to be used in wyoming project with their newest features is limited. It would much better to just use them as libraries even if there is some more diskspace consumption at stake.

**Comment by synesthesiam** [comment]
I've switched to using the `faster-whisper` PyPI package in the 2.0.0 release: https://github.com/rhasspy/wyoming-faster-whisper/releases/tag/v2.0.0
