### ISSUE TITLE
Support for python 3.6

### ISSUE THREAD

**Issue by horvathgergo** [rhasspy/wyoming-faster-whisper#3]
Hi! Currently, python 3.7 is the oldest version that is supported by wyoming-faster-whisper. Are you willing to add support for python 3.6 (NVIDIA Jetson Nano and Jetson TX2 can't be upgraded to higher python versions without losing CUDA acceleration)

**Comment by synesthesiam** [comment]
I would take a PR, but I don't have the time to implement this myself unfortunately.

**Comment by JannickBlmndl** [comment]
Is the Wyoming software stack still unsupported on the Jetson Nano 4GB B01 Dev kit? Or did the implementation of the [Nvidia AI Lab](https://forums.developer.nvidia.com/t/jetson-ai-lab-home-assistant-integration/288225?u=jannick.bloemendal) make any changes? 
Would really love to repurpose the device for voice / LMMs.

**Comment by byrnecore** [comment]
I am trying to use the Jetson nano workign with the voice local voice pipeline. Apparently it can eb done based on the claim here: 
- https://hub.docker.com/r/dustynv/wyoming-piper
- https://github.com/dusty-nv/jetson-containers/blob/master/packages/smart-home/wyoming/docker-compose.yaml

Im pretty new to docker compose so would love anyone helping me and push me in the right direction.
