### ISSUE TITLE
Upgrade to faster-whisper 1.0.2+

### ISSUE THREAD

**Issue by phipolis** [rhasspy/wyoming-faster-whisper#34]
Upstream, faster-whisper added support in version [1.0.2](https://github.com/SYSTRAN/faster-whisper/releases/tag/v1.0.2) for the latest Distil-Whisper model, distil-large-v3.

Downstream, [the Home Assistant addon added](https://github.com/home-assistant/addons/pull/3605) distil-large-v3 to its model schema. Selecting that model fails currently due to [faster-whisper 1.0.1](https://github.com/rhasspy/wyoming-faster-whisper/blob/a5df0d5f02bf3f42d5e89aac241ab65d027c6fb5/requirements.txt#L2) in wyoming-faster-whisper.

**Comment by wuast94** [comment]
+1

**Comment by DavidAntonin** [comment]
Faster-Whisper 1.0.3 is released with performance enhancements.

**Comment by synesthesiam** [comment]
Upgrade to 1.0.3

**Comment by DavidAntonin** [comment]
push please to docker hub
