### ISSUE TITLE
🆕 New model for whisper: turbo

### ISSUE THREAD

**Issue by duhow** [rhasspy/wyoming-faster-whisper#36]
A new model of Whisper `large-v3-turbo` was published https://github.com/openai/whisper/pull/2361

`faster-whisper` does support it in dev version, but no new release was created. https://github.com/SYSTRAN/faster-whisper/commit/b2da05582c78f73e81b0e2d9a8a9e1b46df20a26

**EDIT:** 🆕 Release created: https://github.com/SYSTRAN/faster-whisper/releases/tag/v1.1.0

**Comment by Barsonax** [comment]
I worked around it by doing this: `--model mobiuslabsgmbh/faster-whisper-large-v3-turbo`
