### ISSUE TITLE
Support english-only versions of the whisper models

### ISSUE THREAD

**Issue by jurriaan** [rhasspy/wyoming-faster-whisper#5]
I saw that the english-only versions of the models were available here: https://github.com/rhasspy/models/releases/tag/v1.0

But this add on does not support them (limited by the values in the FasterWhisperModel enum. I tried adding support for these models manually but don't get any working output.

I get these log messages with the `base.en` model, it seems that it does not correctly transcribe the audio:

```
INFO:wyoming_faster_whisper.handler:
INFO:wyoming_faster_whisper.handler:
INFO:wyoming_faster_whisper.handler:
```

**Comment by synesthesiam** [comment]
This is why I didn't include those models. Something is broken with faster-whisper or the conversation process, it seems.
